POST http://localhost:3000/login/ HTTP/1.1
Content-Type:application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###

GET http://localhost:3000/states/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjE4ODM3MzYzfQ.emwdNKafCAQV7W1iyrkmYi63hE2NXgzMbI1XThCsU6k

###